# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ieee_802_15_4.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'ieee_802_15_4.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ieee_802_15_4.proto\"T\n\x07\x43ommand\x12\x1f\n\tconfigure\x18\x01 \x01(\x0b\x32\n.ConfigureH\x00\x12\x1d\n\x08transmit\x18\x02 \x01(\x0b\x32\t.TransmitH\x00\x42\t\n\x07\x63ommand\"/\n\x05\x45vent\x12\x1d\n\x08received\x18\x01 \x01(\x0b\x32\t.ReceivedH\x00\x42\x07\n\x05\x65vent\";\n\x08Received\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x1e\n\x16link_quality_indicator\x18\x02 \x01(\r\"\x1b\n\x08Transmit\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"B\n\tConfigure\x12\x19\n\x07\x63hannel\x18\x01 \x01(\x0e\x32\x08.Channel\x12\x1a\n\x08tx_power\x18\x02 \x01(\x0e\x32\x08.TxPower*\xa3\x01\n\x07\x43hannel\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03\x43\x31\x31\x10\x05\x12\x07\n\x03\x43\x31\x32\x10\n\x12\x07\n\x03\x43\x31\x33\x10\x0f\x12\x07\n\x03\x43\x31\x34\x10\x14\x12\x07\n\x03\x43\x31\x35\x10\x19\x12\x07\n\x03\x43\x31\x36\x10\x1e\x12\x07\n\x03\x43\x31\x37\x10#\x12\x07\n\x03\x43\x31\x38\x10(\x12\x07\n\x03\x43\x31\x39\x10-\x12\x07\n\x03\x43\x32\x30\x10\x32\x12\x07\n\x03\x43\x32\x31\x10\x37\x12\x07\n\x03\x43\x32\x32\x10<\x12\x07\n\x03\x43\x32\x33\x10\x41\x12\x07\n\x03\x43\x32\x34\x10\x46\x12\x07\n\x03\x43\x32\x35\x10K\x12\x07\n\x03\x43\x32\x36\x10P*\xc1\x01\n\x07TxPower\x12\x0c\n\x08POS8D_BM\x10\x00\x12\x0c\n\x08POS7D_BM\x10\x01\x12\x0c\n\x08POS6D_BM\x10\x02\x12\x0c\n\x08POS5D_BM\x10\x03\x12\x0c\n\x08POS4D_BM\x10\x04\x12\x0c\n\x08POS2D_BM\x10\x05\x12\n\n\x06_0D_BM\x10\x06\x12\x0c\n\x08NEG4D_BM\x10\x07\x12\x0c\n\x08NEG8D_BM\x10\x08\x12\r\n\tNEG12D_BM\x10\t\x12\r\n\tNEG16D_BM\x10\n\x12\r\n\tNEG20D_BM\x10\x0b\x12\r\n\tNEG40D_BM\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ieee_802_15_4_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNEL']._serialized_start=317
  _globals['_CHANNEL']._serialized_end=480
  _globals['_TXPOWER']._serialized_start=483
  _globals['_TXPOWER']._serialized_end=676
  _globals['_COMMAND']._serialized_start=23
  _globals['_COMMAND']._serialized_end=107
  _globals['_EVENT']._serialized_start=109
  _globals['_EVENT']._serialized_end=156
  _globals['_RECEIVED']._serialized_start=158
  _globals['_RECEIVED']._serialized_end=217
  _globals['_TRANSMIT']._serialized_start=219
  _globals['_TRANSMIT']._serialized_end=246
  _globals['_CONFIGURE']._serialized_start=248
  _globals['_CONFIGURE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
